const actionTypes = {
  ADD: 'ADD',
  TICK: 'TICK',
  TOGGLE_TODO: 'TOGGLE_TODO',
  TOGGLE_LOGIN: 'TOGGLE_LOGIN',
  // LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  SAVE_TODO: 'SAVE_TODO',
  LOAD_JOKES_SUCCESS: 'LOAD_JOKES_SUCCESS',
  GET_PROFILE: 'GET_PROFILE',
  REFRESH_USER: 'REFRESH_USER',

  // TEST
  ADD_STORE: 'ADD_STORE',
  REFRESH_TOKEN: 'REFRESH_TOKEN',

  // AUTH
  CREATE_USER: 'CREATE_USER',
  SAVE_USER: 'SAVE_USER',
  LOG_OUT: 'LOG_OUT',
  LOG_USER_IN: 'LOG_USER_IN',
  FORGOT_USER: 'FORGOT_USER',
  RESET_PASSWORD: 'RESET_PASSWORD',

  // User Account
  LOAD_USER_DATA: 'LOAD_USER_DATA',
  UPDATE_USER: 'UPDATE_USER',
  GET_USER_HEARTS: 'GET_USER_HEARTS',

  // Reviews
  ADD_RATING: 'ADD_RATING',
  ADD_RATING_STORE: 'ADD_RATING_STORE',

  // STORE
  SAVE_STORE: 'SAVE_STORE',
  GET_SINGLE_STORE: 'GET_SINGLE_STORE',
  LOAD_SINGLE_STORE_SUCCESS: 'LOAD_SINGLE_STORE_SUCCESS',
  LOAD_STORE_DATA: 'LOAD_STORE_DATA',
  UPDATE_STORE_DATA: 'UPDATE_STORE_DATA',
  LOAD_STORES_SUCCESS: 'LOAD_STORES_SUCCESS',
  LOAD_TAG_LIST_SUCCESS: 'LOAD_TAG_LIST_SUCCESS',
  GET_FAV_STORES: 'GET_FAV_STORES',
  HEART_TOGGLE: 'HEART_TOGGLE'
}

export default actionTypes
